#!/usr/bin/env ruby

######################################################################################
# outputs general system informations
# 2020-10-28_08:45:47 raspberrypi4: up 57 minutes - local 192.168.1.69 remote:84.149.140.5 mem_used:23.7% temp=50.0'C - System: Linux raspberrypi4 5.4.51-v7l+ #1333 SMP Mon Aug 10 16:51:40 BST 2020 armv7l
# put this to cron like
# */5 * * * * sudo raspberrypi/scripts/raspi-info >> /data/backups/`hostname`.log 2>&1
######################################################################################

temp = `vcgencmd measure_temp`.strip
sys_info= `uname -a`.strip
uptime=`uptime -p`.strip
local_ip=`ifconfig eth0 | grep -w "inet" | tr -s " " | cut -f3 -d" "`.strip
remote_ip=`dig +short myip.opendns.com @resolver1.opendns.com`.strip
memory_used=`free | grep Mem | awk '{print $3/$2 * 100.0}'`.strip.to_f.round(1)
hostname=`hostname`.strip

puts "#{Time.now.strftime("%Y-%m-%d_%H:%M:%S")} #{hostname}: #{uptime} - local #{local_ip} remote:#{remote_ip} mem_used:#{memory_used}% #{temp} - System: #{sys_info}"
