#!/usr/bin/env ruby
temp = `vcgencmd measure_temp`.strip
sys_info= `uname -a`.strip
uptime=`uptime -p`.strip
local_ip=`ifconfig eth0 | grep -w "inet" | tr -s " " | cut -f3 -d" "`.strip
remote_ip=`dig +short myip.opendns.com @resolver1.opendns.com`.strip
memory_used=`free | grep Mem | awk '{print $3/$2 * 100.0}'`.strip.to_f.round(1)
hostname=`hostname`.strip

puts "#{Time.now.strftime("%Y-%m-%d_%H:%M:%S")} #{hostname}: #{uptime} - local #{local_ip} remote:#{remote_ip} mem_used:#{memory_used}% #{temp} - System: #{sys_info}"
